# Generated by Django 3.2.6 on 2021-08-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_file',
            field=models.ImageField(default='image_file_empty', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='post',
            name='img_name',
            field=models.CharField(default='default-img-name', max_length=200),
        ),
    ]
